apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "test-spring-service"
  description: "hackweek-spring just testing"
  annotations:
    github.com/project-slug: mikevanwinklesonos/testspring2
    backstage.io/techdocs-ref: url:https://github.com/mikevanwinklesonos/testspring2
spec:
  type: openapi
  lifecycle: experimental
  owner: "cloud-traffic"
  system: platform
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
